### ISSUE TITLE
Nice! Purple in Mobile?

### ISSUE THREAD

**Issue by laurentopia** [AJTech2002/Grass-Shader-Tutorial#1]
Do you know what would make it purple in Mobile?
Awesome in desktop!

**Comment by AJTech2002** [comment]
You may have to look into what devices support geometry shaders, it may not be possible on some mobile phones. Sorry about that, another alternative is to use GPU Instanced grass.

**Comment by laurentopia** [comment]
It supports geometry shaders (switch)

**Comment by AJTech2002** [comment]
If the device supports the geometry shader then it could be a build issue, you might have to add the shader to the 'Always Included Shaders' in the Player Settings. This stackoverflow thread goes over how to accomplish this:

https://stackoverflow.com/questions/44731478/ui-pink-on-android-device

You might also want to look at this link to see if you are hitting any limitations:

https://docs.unity3d.com/Manual/OpenGLCoreDetails.html

**Comment by laurentopia** [comment]
same pink
like that?
![image](https://user-images.githubusercontent.com/26075468/95566255-2c8cac00-09d6-11eb-9366-63b34b2a8aff.png)

**Comment by laurentopia** [comment]
somehow it works now, dreadfully slow on a switch so maybe it's what you mentioned about double draw but what I think is the geometry shader unit in the Tegra x1 is under developed
